title: ""  # リポジトリ名を非表示にする

# アセットの設定
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/css

# アセットのインクルード設定
include:
  - assets
  - _sass

# テーマ設定
theme: null  # デフォルトテーマを無効化